name: Publish to PyPI.org
on:
  push:
    tags:
      - v1.*
      - v0.*
jobs:
  test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: python3 -m venv venv
      - run: source venv/bin/activate
      - run: pip install --upgrade pip
      - run: sudo pip install --upgrade pip
      - run: pip install --user tox
      - run: tox
  publish:
    runs-on: ubuntu-latest
    needs: test-lint
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: python3 -m pip install --upgrade build && python3 -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
